config_file: config/nanodet-plus-m-1.5x_416.yml
epochs: 100
input_size: -1  # use -1 to use the default input size
learning_rate: -1  # use -1 to use default learning rate in config file
batch_size_per_gpu: 16
workers_per_gpu: 4
resume: False
shm_size: 128G
export_format: 'ark:raw'
load_from: '/weights/nanodet-plus-m-1.5x_416.pth'
ddp_debug: False  # debug for ddp training
profiler: False  # profile model
